//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookVarApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopAddressLink
    {
        public int ShopAddressLinkID { get; set; }
        public Nullable<int> ShopID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public int ShopAddressLinkAvailability { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
